export const CAT_BREEDS = [
  {
    id: 'munchkin',
    name: '曼赤肯',
    nameEn: 'Munchkin',
    type: 'cat',
    ascii: [
      '  /\\_/\\  ',
      ' ( o.o ) ',
      '  > ^ <  ',
      ' /|   |\\ ',
      '(_|   |_)',
    ],
    stats: { hp: 85, atk: 50, def: 45, spd: 70, spc: 70 },
    skill: '低空突襲',
    skillDesc: '利用矮小身材閃避後反擊',
    skillKind: 'dash',
    color: '#D4A574',
  },
  {
    id: 'persian',
    name: '波斯貓',
    nameEn: 'Persian',
    type: 'cat',
    ascii: [
      ' ~\\_/\\_/~ ',
      ' ( -.- )  ',
      '  = ^ =   ',
      ' /|~~~|\\ ',
      '(_|   |_)',
    ],
    stats: { hp: 95, atk: 45, def: 60, spd: 35, spc: 85 },
    skill: '華麗毛球',
    skillDesc: '甩出華麗毛髮造成範圍傷害',
    skillKind: 'burst',
    color: '#F5E6D3',
  },
  {
    id: 'siamese',
    name: '暹羅貓',
    nameEn: 'Siamese',
    type: 'cat',
    ascii: [
      '  /\\_/\\  ',
      ' ( ◗.◗ ) ',
      '  > ^ <  ',
      '  |/ \\|  ',
      '  (_@_)  ',
    ],
    stats: { hp: 75, atk: 65, def: 30, spd: 85, spc: 65 },
    skill: '尖叫音波',
    skillDesc: '高頻叫聲造成暈眩效果',
    skillKind: 'strike',
    color: '#C4A882',
  },
  {
    id: 'scottish_fold',
    name: '蘇格蘭摺耳',
    nameEn: 'Scottish Fold',
    type: 'cat',
    ascii: [
      '  __v__  ',
      ' ( o.o ) ',
      '  > ^ <  ',
      '  |/ \\|  ',
      '  (___) ',
    ],
    stats: { hp: 100, atk: 45, def: 75, spd: 30, spc: 70 },
    skill: '圓球防禦',
    skillDesc: '蜷成球狀大幅提升防禦',
    skillKind: 'shield',
    color: '#B8A590',
  },
  {
    id: 'maine_coon',
    name: '緬因貓',
    nameEn: 'Maine Coon',
    type: 'cat',
    ascii: [
      ' /\\\\_/\\\\ ',
      '( O . O )',
      ' => ^ <= ',
      ' /|===|\\ ',
      '(_|   |_)',
    ],
    stats: { hp: 115, atk: 60, def: 60, spd: 35, spc: 50 },
    skill: '巨爪鐵壁',
    skillDesc: '以龐大身軀抵禦傷害',
    skillKind: 'shield',
    color: '#8B7355',
  },
  {
    id: 'bengal',
    name: '孟加拉貓',
    nameEn: 'Bengal',
    type: 'cat',
    ascii: [
      '  /\\_/\\  ',
      ' (*ö.ö*) ',
      '  >*^*<  ',
      '  |/~\\|  ',
      '  (_*_)  ',
    ],
    stats: { hp: 80, atk: 75, def: 40, spd: 75, spc: 50 },
    skill: '豹紋疾步',
    skillDesc: '野性突進連續攻擊',
    skillKind: 'dash',
    color: '#C4943A',
  },
  {
    id: 'ragdoll',
    name: '布偶貓',
    nameEn: 'Ragdoll',
    type: 'cat',
    ascii: [
      '  /\\_/\\  ',
      ' ( ^.^ ) ',
      '  > ~ <  ',
      ' /|~~~|\\ ',
      '(~|   |~)',
    ],
    stats: { hp: 100, atk: 40, def: 55, spd: 40, spc: 85 },
    skill: '柔體術',
    skillDesc: '軟綿綿地避開所有攻擊',
    skillKind: 'heal',
    color: '#E8DDD0',
  },
  {
    id: 'russian_blue',
    name: '俄羅斯藍貓',
    nameEn: 'Russian Blue',
    type: 'cat',
    ascii: [
      '  /\\_/\\  ',
      ' ( °.° ) ',
      '  > ^ <  ',
      '  |/ \\|  ',
      '  (___) ',
    ],
    stats: { hp: 80, atk: 55, def: 55, spd: 60, spc: 70 },
    skill: '冰霜凝視',
    skillDesc: '冷酷眼神降低對手攻擊',
    skillKind: 'strike',
    color: '#8BA4B8',
  },
  {
    id: 'sphynx',
    name: '斯芬克斯',
    nameEn: 'Sphynx',
    type: 'cat',
    ascii: [
      '  /\\ /\\  ',
      ' (  o  ) ',
      '  | ^ |  ',
      '  |/ \\|  ',
      '  (___) ',
    ],
    stats: { hp: 65, atk: 55, def: 30, spd: 85, spc: 85 },
    skill: '神祕詛咒',
    skillDesc: '古埃及詛咒持續掉血',
    skillKind: 'burst',
    color: '#D4B896',
  },
  {
    id: 'british_shorthair',
    name: '英國短毛',
    nameEn: 'British Shorthair',
    type: 'cat',
    ascii: [
      '  _\\_/_  ',
      ' ( ō.ō ) ',
      '  > ^ <  ',
      ' /|===|\\ ',
      '(_|___|_)',
    ],
    stats: { hp: 110, atk: 45, def: 65, spd: 30, spc: 70 },
    skill: '紳士午茶',
    skillDesc: '優雅地補充下午茶恢復體力',
    skillKind: 'heal',
    color: '#7B8B9E',
  },
];

export const DOG_BREEDS = [
  {
    id: 'husky',
    name: '哈士奇',
    nameEn: 'Husky',
    type: 'dog',
    ascii: [
      ' /\\   /\\ ',
      '(  \\ /  )',
      ' ( o o ) ',
      '  | W |  ',
      '  |___|  ',
    ],
    stats: { hp: 90, atk: 60, def: 45, spd: 70, spc: 55 },
    skill: '暴風嚎叫',
    skillDesc: '刺耳嚎叫降低敵方速度',
    skillKind: 'burst',
    color: '#A0B4C8',
  },
  {
    id: 'golden',
    name: '黃金獵犬',
    nameEn: 'Golden Retriever',
    type: 'dog',
    ascii: [
      ' /\\___/\\ ',
      '(  ^ ^  )',
      ' ( =W= ) ',
      ' /|~~~|\\ ',
      '(_|   |_)',
    ],
    stats: { hp: 110, atk: 50, def: 55, spd: 45, spc: 60 },
    skill: '友善撲擊',
    skillDesc: '熱情擁抱造成傷害並回血',
    skillKind: 'heal',
    color: '#DAA520',
  },
  {
    id: 'shiba',
    name: '柴犬',
    nameEn: 'Shiba Inu',
    type: 'dog',
    ascii: [
      ' /\\   /\\ ',
      '| (• •) |',
      ' \\  W  / ',
      '  |/ \\|  ',
      '  (___) ',
    ],
    stats: { hp: 90, atk: 65, def: 55, spd: 60, spc: 50 },
    skill: 'Doge光線',
    skillDesc: 'Much damage. Very wow.',
    skillKind: 'strike',
    color: '#E8A840',
  },
  {
    id: 'corgi',
    name: '柯基',
    nameEn: 'Corgi',
    type: 'dog',
    ascii: [
      ' /\\   /\\ ',
      '( o   o )',
      ' \\ =W= / ',
      ' |=====| ',
      ' (__@__) ',
    ],
    stats: { hp: 90, atk: 50, def: 55, spd: 55, spc: 70 },
    skill: '短腿衝鋒',
    skillDesc: '低重心全力衝撞',
    skillKind: 'dash',
    color: '#D4923A',
  },
  {
    id: 'poodle',
    name: '貴賓犬',
    nameEn: 'Poodle',
    type: 'dog',
    ascii: [
      '  @@@@@  ',
      ' ( o o ) ',
      '  ( W )  ',
      '  |@@@|  ',
      '  (_@_)  ',
    ],
    stats: { hp: 75, atk: 45, def: 40, spd: 70, spc: 90 },
    skill: '華麗旋轉',
    skillDesc: '旋轉跳躍的範圍魔法攻擊',
    skillKind: 'burst',
    color: '#F0E0F0',
  },
  {
    id: 'german_shepherd',
    name: '德國牧羊犬',
    nameEn: 'German Shepherd',
    type: 'dog',
    ascii: [
      ' /\\   /\\ ',
      '|  \\ /  |',
      '( ◉ ◉ ) ',
      '  |=W=|  ',
      ' /|   |\\ ',
    ],
    stats: { hp: 95, atk: 75, def: 55, spd: 45, spc: 50 },
    skill: '戰術回血',
    skillDesc: '戰地急救包恢復戰力',
    skillKind: 'heal',
    color: '#5C4033',
  },
  {
    id: 'border_collie',
    name: '邊境牧羊犬',
    nameEn: 'Border Collie',
    type: 'dog',
    ascii: [
      '  /\\ /\\  ',
      ' ( o.o ) ',
      '  |=W=|  ',
      ' /|===|\\ ',
      ' (_|_|_) ',
    ],
    stats: { hp: 80, atk: 50, def: 45, spd: 70, spc: 75 },
    skill: '牧羊凝視',
    skillDesc: '專注眼神鎖定目標，提升命中與暴擊',
    skillKind: 'strike',
    color: '#3A3A3A',
  },
  {
    id: 'bulldog',
    name: '鬥牛犬',
    nameEn: 'Bulldog',
    type: 'dog',
    ascii: [
      '  _---_  ',
      ' ( o o ) ',
      '(  =W=  )',
      ' \\|===|/ ',
      ' (_____) ',
    ],
    stats: { hp: 120, atk: 60, def: 70, spd: 30, spc: 40 },
    skill: '鐵壁防線',
    skillDesc: '堅不可摧的防禦姿態',
    skillKind: 'shield',
    color: '#C4A882',
  },
  {
    id: 'dalmatian',
    name: '大麥町',
    nameEn: 'Dalmatian',
    type: 'dog',
    ascii: [
      ' /\\.  /\\ ',
      '( .o o. )',
      ' \\ .W. / ',
      '  |.=.|  ',
      '  (._.)  ',
    ],
    stats: { hp: 85, atk: 60, def: 45, spd: 80, spc: 50 },
    skill: '斑點亂舞',
    skillDesc: '高速移動產生殘影迷惑敵人',
    skillKind: 'dash',
    color: '#F5F5F5',
  },
  {
    id: 'akita',
    name: '秋田犬',
    nameEn: 'Akita',
    type: 'dog',
    ascii: [
      ' /\\   /\\ ',
      '|  ===  |',
      '( • _ • )',
      '  |===|  ',
      ' (_____) ',
    ],
    stats: { hp: 110, atk: 65, def: 60, spd: 35, spc: 50 },
    skill: '忠義鐵壁',
    skillDesc: '以忠誠守護自身，抵禦敵方攻擊',
    skillKind: 'shield',
    color: '#CD853F',
  },
];

export const ALL_CHARACTERS = [...CAT_BREEDS, ...DOG_BREEDS];

export function getCharacterById(id) {
  return ALL_CHARACTERS.find(c => c.id === id);
}
